export const SITE = {
  website: "https://www.alpcakin.com/",
  author: "Alp Çakın",
  profile: "https://github.com/alpcakin",
  desc: "Full-stack developer building web and mobile products — from a POS platform for small retailers to a fintech alert system. Also writes about macroeconomics and market dynamics.",
  title: "alpcakin",
  ogImage: "",
  lightAndDarkMode: false,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000, // 15 minutes
  showArchives: false,
  showGalleries: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit this post",
    url: "https://github.com/alpcakin/alpcakin.github.io/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Europe/Paris",
  introAudio: {
    enabled: false,
    src: "/audio/intro-web.mp3",
    label: "INTRO.MP3",
    duration: 30,
  },
} as const;
